### ISSUE TITLE
Would be interested in a writeup of learnings.

### ISSUE THREAD

**Issue by Qix-** [graydon/berlin#1]
Hey there, this looks neat. I appreciate that you've shared it.

I know it's a lot to ask, but I would be absolutely thrilled to hear of a list of things you learned throughout the process of creating a windowing system. It might seem niche but I assure you it's relevant to far more people than one might think - and, at the very least, certainly very interesting.

If you're willing to document rants, raves, or any sort of lessons-learned, at least one person would be thrilled to read about them.

Either way, thanks for making this public :)

**Comment by graydon** [comment]
Oh gosh. I mean, it was a _long_ time ago. 20 years now! Everything possible has changed, from languages to graphics interfaces to hardware to expectations of what you want to do with a computer. I doubt there's much learnable (and I hardly remember anything). It was my first open source project (in fact the project started before the term "open source" had even been coined) and my first C++ project, and I was really just a kid. Also I only worked on it for maybe half this time period, Stefan was really a much better coder than me (and actually knew linear algebra).

**Comment by Qix-** [comment]
Haha no worries, was a shot in the dark! Thanks for the response, and happy new year :)
